helloWorld/config/routes.rb
Rails.application.routes.draw do
  get 'show_time/index'

  get 'cinemas/index'

  get 'welcome/index'

  root 'welcome#index'

end

helloWorld/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

helloWorld/app/controllers/cinema_controller.rb
class CinemaController < ApplicationController
  @@cinemas_on_screen = {'24'=>['9.00AM','12.00AM','8.00PM'],'Kabali'=>['12.00PM','6.00PM'],'Kamattipadam'=>['10.00AM','3.00PM']}
  def index
  end
  def cinema_list
    @running_cinemas = @@cinemas_on_screen.keys
  end
  def show_time
    @show_times = @@cinemas_on_screen
  end
end

helloWorld/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  @@userName = 'arun'
  @@userPassword = '12345'

  def index
    if request.method.eql? 'POST'
      name = params[:welcome][:name]
      password = params[:welcome][:password]
      if (@@userName.eql? name) &&(@@userPassword.eql? password)
        redirect_to url_for(:controller => :cinema, :action => :index)
      else
        @warning = "wrong password or user name,Try again"
      end
    end
  end

end

helloWorld/app/helpers/cinema_helper.rb
module CinemaHelper
end

helloWorld/app/helpers/cinemas_helper.rb
module CinemasHelper
end

helloWorld/app/helpers/show_time_helper.rb
module ShowTimeHelper
end

helloWorld/app/views/cinema/cinema_list.erb
<%= stylesheet_link_tag 'cinema_list.css' %>
<table>
  <tr>CINEMAS</tr>
  <% @running_cinemas.each do |movieName| %>
      <tr>
        <td>
          <%= movieName %>
        </td>
      </tr>

  <% end %>
</table>
<!--<h1><%= @running_cinemas %></h1>-->
<%= button_to 'Back To Home', cinema_index_path, :method => :post %>

helloWorld/app/views/cinema/index.html.erb
<%= stylesheet_link_tag 'index.css' %>
<h1>Home</h1>
<%= button_to 'Cinemas On Screen', { :action => 'cinema_list' }, :method => :get %>
<%= button_to 'Show Time', { :action => 'show_time' }, :method => :get %>

helloWorld/app/views/cinema/show_time.erb
<%= stylesheet_link_tag 'show_time.css' %>
<table>
  <th>Movie</th>
  <th>Time</th>
  <% @show_times.each { |movie| %>
      <tr>
        <td>
          <%= movie[0] %>
        </td>
        <td>
          <%= movie[1].join(', ') %>
        </td>
      </tr>

  <% }%>

</table>
<%= button_to 'Back To Home', cinema_index_path, :method => :post %>

helloWorld/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

helloWorld/app/views/welcome/index.html.erb
<h1>Log In</h1>
<h2><%=@warning%></h2>
<%= form_for :welcome do |f| %>
    Name: <%= f.text_field :name %><br />
    password : <%= f.text_field :password %><br />
    <%= f.submit %>
<% end %>